### ISSUE TITLE
Recursive queries do return results when using a callback

### ISSUE THREAD

**Issue by scottrudy** [Learnosity/learnosity-sdk-asp.net#35]
Each request response only gets merged into the overall result if a callback is not present when using the DataAPI with the SDK. If a callback is used then the response will be an empty JsonObject. I have submitted PR #34 which addresses this problem and includes an integration test to prevent any issues going forward.

**Comment by flakeparadigm** [comment]
Hi @scottrudy,
Thanks for submitting this issue and the PR to fix it. We've added it into our backlog for developer review and we'll make sure to keep you updated on the progress.

**Comment by flakeparadigm** [comment]
Hi @scottrudy,
Since the current behaviour is intentional, we would like to know more about your use case to ensure that we make the right decision.

What are you aiming to achieve by using both a callback and the final result, but are not able to do with only one or the other?

**Comment by scottrudy** [comment]
It appears the intent of the callback is to allow the calling function to make the determination that it has enough data and can stop getting more data. The current implementation returns no data if a callback is used. The integration test I included will show the behavior I am referring to as it is now.

**Comment by flakeparadigm** [comment]
Ahh, perhaps there's a shortcoming in our documentation.

The intent of the callback is that you can process the data that is received incrementally. This is especially important for very large datasets where you may not want to keep all of the results in memory, but instead aggregate or process them in smaller chunks.

If you need to use the callback to determine when to stop fetching more results, would it also be possible to use the callback to merge each chunk into your own results array?

**Comment by scottrudy** [comment]
I see. Yes it does seem like there is a disconnect in the usage then. I suppose it would be possible for the callback to perform the merge. Although the return value from the function being null in that case feels weird.

**Comment by scottrudy** [comment]
I think it is strange that a response is sent back when it's only going to be null if there is a callback. If that's the intention then why not just return null directly and explain the return value in the function's XML comments.

**Comment by scottrudy** [comment]
Also, looking at the included [example in the SDK](https://github.com/Learnosity/learnosity-sdk-asp.net/blob/f05ed67252fb9da6136bba1c50bf169ef98803e9/LearnositySDK/Examples/Data.cs#L88) it seems to have the same expectation I did, that the response will have a value.

**Comment by flakeparadigm** [comment]
Thanks for the feedback. After looking through everything, we've concluded that the current behaviour should remain as-is. While the fact that it does return that partial value is a bit strange (and doesn't match [other SDKs](https://github.com/Learnosity/learnosity-sdk-php/blob/master/src/LearnositySdk/Request/DataApi.php#L86-L90)), the general behaviour is ultimately intentional and changing what it returns would be a breaking change to an API many people use.

In lieu of changes to the SDK itself we will update the documentation and examples to make the intended use cases more clear. If you wish to receive updates about these changes, feel free to leave this issue open.

Internal tracking: CAT-368

**Comment by monet-slinowsky-lrn** [comment]
This issue is closed
